import {measurementKeys,type MeasurementReport,type MeasurementEstimate,type Unit} from '@/lib/measurement/types';
export const PROFILE_KEY='contourstitch.profile.v1';
// Compatibility only: keep existing saved profiles readable and deletable.
const LEGACY_PROFILE_KEY='fittingroom.profile.v1';
export type LocalProfile={version:1;unit:Unit;report:MeasurementReport};
/** Allowlist reconstruction: raw photos, landmarks and masks cannot enter storage. */
export function sanitizeProfile(input:unknown):LocalProfile|null{if(!input||typeof input!=='object')return null;const value=input as Partial<LocalProfile>;if(value.version!==1||(value.unit!=='cm'&&value.unit!=='in')||!value.report||!Array.isArray(value.report.estimates)||value.report.estimates.length>8)return null;const estimates:MeasurementEstimate[]=[];for(const item of value.report.estimates){if(!item||!measurementKeys.includes(item.key)||estimates.some(e=>e.key===item.key)||!Number.isFinite(item.valueCm)||item.valueCm<=0||item.valueCm>300||!Number.isFinite(item.uncertaintyCm)||item.uncertaintyCm<0||item.uncertaintyCm>300||!['low','medium','high'].includes(item.confidence)||typeof item.method!=='string'||item.method.length>500||!Array.isArray(item.warnings)||item.warnings.some(w=>typeof w!=='string'||w.length>500))return null;estimates.push({key:item.key,valueCm:item.valueCm,uncertaintyCm:item.uncertaintyCm,confidence:item.confidence,method:item.method,warnings:[...item.warnings]});}const missing:MeasurementReport['missing']={};for(const key of measurementKeys){const reason=value.report.missing?.[key];if(typeof reason==='string'&&reason.length<=500)missing[key]=reason;}return {version:1,unit:value.unit,report:{estimates,missing}};}
export function saveProfile(report:MeasurementReport,unit:Unit){const profile=sanitizeProfile({version:1,report,unit});if(!profile)throw new Error('Invalid measurements');window.localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));window.localStorage.removeItem(LEGACY_PROFILE_KEY);}
export function loadProfile():LocalProfile|null{const stored=window.localStorage.getItem(PROFILE_KEY)??window.localStorage.getItem(LEGACY_PROFILE_KEY);if(!stored)return null;try{return sanitizeProfile(JSON.parse(stored));}catch{return null;}}
export const deleteProfile=()=>{window.localStorage.removeItem(PROFILE_KEY);window.localStorage.removeItem(LEGACY_PROFILE_KEY);};
