'use client';
import {useEffect,useRef,useState} from 'react';
import {SwitchCamera,Camera} from 'lucide-react';
import {requestCamera,releaseCamera,cameraError} from '@/lib/camera/media';
import {createVisionEngine} from '@/lib/vision/pose';
import {assessQuality} from '@/lib/vision/quality';
import {config} from '@/lib/measurement/config';
import type {Capture,View,VisionEngine,VisionFrame} from '@/lib/vision/types';
import {BodyGuide} from './BodyGuide';
import {DebugReview} from './DebugReview';
import {PoseOverlay} from './PoseOverlay';
import {CaptureChecklist} from './CaptureChecklist';
export function CameraView({view,onCapture,onManual,engineFactory=createVisionEngine}:{view:View;onCapture:(capture:Capture)=>void;onManual:()=>void;engineFactory?:()=>Promise<VisionEngine>}){const video=useRef<HTMLVideoElement>(null);const [facing,setFacing]=useState<'environment'|'user'>('environment');const [attempt,setAttempt]=useState(0);const [state,setState]=useState<{frame:VisionFrame|null;error:string;status:string}>({frame:null,error:'',status:'Preparing your camera…'});const [override,setOverride]=useState(false);const [review,setReview]=useState<Capture|null>(null);const current=useRef<VisionFrame|null>(null);
useEffect(()=>{let cancelled=false,stream:MediaStream|null=null,engine:VisionEngine|null=null,timer:ReturnType<typeof setTimeout>|undefined;current.current=null;function clearFrame(){current.current=null;setState(s=>({...s,frame:null,status:'Adjusting to the new camera orientation…'}));}function stop(){cancelled=true;clearTimeout(timer);releaseCamera(stream);engine?.close();current.current=null;if(video.current)video.current.srcObject=null;}function visibility(){if(document.hidden){stop();setState({frame:null,error:'Camera paused while the page was hidden. Try again to resume.',status:''});}}window.addEventListener('orientationchange',clearFrame);document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',stop);
async function start(){try{stream=await requestCamera(facing);if(cancelled){releaseCamera(stream);return;}const element=video.current;if(!element)throw new Error('Preview missing');element.srcObject=stream;await element.play();setState({frame:null,error:'',status:'Loading the private on-device model…'});engine=await engineFactory();if(cancelled){engine.close();return;}async function tick(){if(cancelled||!engine)return;try{if(element&&element.readyState>=2&&element.videoWidth){const frame=await engine.infer(element);if(cancelled)return;current.current=frame;setState({frame,error:'',status:'Camera ready. Follow the checklist below.'});}timer=setTimeout(tick,config.inferenceIntervalMs);}catch(error){stop();setState({frame:null,error:cameraError(error),status:''});}}void tick();}catch(error){stop();if(video.current)setState({frame:null,error:cameraError(error),status:''});}}void start();return ()=>{stop();window.removeEventListener('orientationchange',clearFrame);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',stop);};},[facing,attempt,engineFactory]);
const quality=state.frame?assessQuality(state.frame,view):null;const ready=!!quality&&quality.checks.every(check=>check.passed);const canCapture=!!state.frame&&!!state.frame.mask&&state.frame.landmarks.length>0&&(ready||override);function capture(){const frame=current.current;if(!frame||performance.now()-frame.timestamp>config.maxFrameAgeMs){setState(s=>({...s,error:'The preview is stale. Hold still and try again.'}));return;}setReview({...frame,view,quality:{...assessQuality(frame,view),override}});}
return <div><p className="muted">{view==='front'?'Ask a helper to hold the rear camera level around waist height. Stand barefoot in fitted clothing, 2–3 metres away.':'Turn 90° to the side at the same distance. Stand naturally and move your arms slightly forward so your torso outline stays visible.'}</p><div className="camera-preview" style={{aspectRatio:state.frame?`${state.frame.width}/${state.frame.height}`:'3/4'}}><div className={facing==='user'?'camera-source mirrored':'camera-source'}><video ref={video} autoPlay muted playsInline aria-label={`${view} camera preview`}/>{state.frame&&<PoseOverlay landmarks={state.frame.landmarks} width={state.frame.width} height={state.frame.height}/>}</div><BodyGuide side={view==='side'}/><div className="level-indicator">{quality?`${Math.round(quality.tiltDegrees)}° body tilt`:'Align the camera level'}</div></div><p role="status" className="muted">{state.status}</p>{state.error&&<div className="error" role="alert"><p>{state.error}</p><button type="button" className="secondary-button" onClick={()=>{setState({frame:null,error:'',status:'Trying your camera again…'});setAttempt(v=>v+1);}}>Try camera again</button></div>}{quality&&<CaptureChecklist checks={quality.checks}/>}<button className="text-button camera-switch" type="button" onClick={()=>{setReview(null);setState({frame:null,error:'',status:'Switching camera…'});setFacing(f=>f==='environment'?'user':'environment');}}><SwitchCamera size={18}/> Switch camera · {facing==='environment'?'rear':'front'}</button>{review?<div className="review-box">{process.env.NODE_ENV==='development'&&new URLSearchParams(window.location.search).get('debug')==='1'&&<DebugReview capture={review}/>}<h3>{view==='front'?'Front':'Side'} capture recorded</h3><p>Check your pose before continuing. Only the detected outline and landmarks are kept temporarily.</p>{review.quality.override&&<p className="error">Quality checks were overridden. Accuracy may be reduced.</p>}<button className="button" onClick={()=>onCapture(review)}>Use {view} capture →</button><button className="text-button" onClick={()=>setReview(null)}>Retake photo</button></div>:<><label className="consent"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/> Capture despite quality warnings — potentially reduces accuracy.</label><button className="button" disabled={!canCapture} onClick={capture}><Camera size={18}/> Capture {view} photo</button></>}<button className="text-button" onClick={onManual}>Enter tape measurements instead</button></div>;}
